[package]
name = "oolisp"
version = "0.1.9"
authors = ["hgking <hgmaxwellking@gmail.com>"]
edition = "2018"
description = "LISP based on Daniel Holden's Book, compiles to web assembly"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7"
wasm-bindgen = "0.2"
